import { Inter } from "next/font/google";
import "./globals.css";

import SessionProvider from "./components/SessionProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "E-Commerce Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          <nav>

          </nav>

          <main className="">
            {children}
          </main>
          <footer></footer>
        </SessionProvider>
      </body>
    </html>
  );
}
